language: python
python:
  - "3.6"
env: NGROK_TOKEN=1c1uvy5CSMYBuO3o7Jv3xgRugYF_XGEz3Atyjb7KMaxw5GeU
before_install:
  - sudo apt-get update
  - sudo apt-get install zfsutils-linux

script:
  # - sudo -E ./ngrok.sh
  - sudo -E ./run_tests
  # - sudo -E pip --version
