language: python
python:
  - "3.6"
env: NGROK_TOKEN=1c1uvy5CSMYBuO3o7Jv3xgRugYF_XGEz3Atyjb7KMaxw5GeU
before_install:
  - sudo apt-get update
  - sudo apt-get install zfsutils-linux
before_script: 
  - pip --version
script:
  - sudo -E pip --version
  - sudo -E ./ngrok.sh
