language: python
python:
  - "3.6"
  - "2.7"
dist:
  - xenial
  - bionic
  
before_install:
  - sudo apt-get update
  - sudo apt-get install zfsutils-linux

script:
  # - sudo -E ./ngrok.sh
  - sudo -E ./run_tests
  # - sudo -E pip --version
