name: Regression tests


on:
  workflow_dispatch:
  


jobs:
     
  ubuntu16:
    runs-on: ubuntu-16.04
    steps:
     - name: Prepare
       run: sudo apt-get install zfsutils-linux
       
     - name: Regression test
       run: pwd; ls ..
       
       
           
       
      
