name: Regression tests

on:
  workflow_dispatch:
  

jobs:
  ubuntu16:
    runs-on: ubuntu-16.04
    steps:
     - name: Regression test
       run: id; uname -a; dmesg
       
           
       
      
