name: Regression tests


on:
  workflow_dispatch:
  push:
    branches: 
      - master
  


jobs:
     
  ubuntu16:
    runs-on: ubuntu-16.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
       
      - name: Prepare
        run: sudo apt-get install zfsutils-linux && sudo pip3 install coverage unittest2 mock==3.0.5
       
       
      - name: Regression test
        run: sudo -E ./run_tests
        
        
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
       
       
           
       
      
