name: Regression tests


on:
  workflow_dispatch:
  push:
    branches: 
      - master
  


jobs:
     
  ubuntu16:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
       
      - name: Prepare
        run: sudo apt-get install zfsutils-linux
       
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
       
      - name: Regression test
        run: ls; sudo -E ./run_tests
      
       
       
           
       
      
